# Generated by Django 5.2 on 2026-06-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'user'), (2, 'admin'), (3, 'superuser')], default=1),
        ),
    ]
